INSERT INTO uporabnik (ime, priimek, uporabniskoIme, email, naslov, password) VALUES ('Petra', 'Kos', 'petrakos', 'petra.kos@hotmail.com', 'Celovska cesta 20, 1000 Ljubljana', 'geslo');
INSERT INTO uporabnik (ime, priimek, uporabniskoIme, email, naslov, password) VALUES ('Miha', 'Novak', 'mihanovak', 'miha.novak@gmail.com', 'Dunajska 155, 1000 Ljubljana', 'geslo');
INSERT INTO uporabnik (ime, priimek, uporabniskoIme, email, naslov, password) VALUES ('Blaž', 'Mahnič', 'blazmahnic', 'blaz.mahnic@gmail.com', 'Parož 2, 3204 Dobrna', 'geslo');
INSERT INTO uporabnik (ime, priimek, uporabniskoIme, email, naslov, password) VALUES ('Petra', 'Boc', 'petraboc', 'petra.boc@gmail.com', 'Karlovška cesta 17, 1000 Ljubljana', 'geslo');
INSERT INTO uporabnik (ime, priimek, uporabniskoIme, email, naslov, password) VALUES ('Petra', 'Deržaj', 'petraderzaj', 'petra.derzaj@gmail.com', 'Zadlog 55, 5274 Crni vrh nad Idrijo', 'geslo');
INSERT INTO uporabnik (ime, priimek, uporabniskoIme, email, naslov, password) VALUES ('Ela', 'Dev', 'eladev', 'ela.dev@gmail.com', 'Trdinova ulica 5, 8000 Novo Mesto', 'geslo');
INSERT INTO uporabnik (ime, priimek, uporabniskoIme, email, naslov, password) VALUES ('Maj', 'Grabnar', 'majgrabnar', 'maj.grabnar@gmail.com', 'Gornje Vreme 34, 6217 Vremski Britof', 'geslo');
INSERT INTO uporabnik (ime, priimek, uporabniskoIme, email, naslov, password) VALUES ('Ula', 'Merljak', 'ulamerljak', 'ula.merljak@gmail.com', 'Bukovica 43, 4227 Selca', 'geslo');
INSERT INTO uporabnik (ime, priimek, uporabniskoIme, email, naslov, password) VALUES ('Oliver', 'Bezjak', 'oliverBezjak', 'oliver.bezjak@gmail.com', 'Novljanska cesta 4, 4205 Preddvor', 'geslo');
INSERT INTO uporabnik (ime, priimek, uporabniskoIme, email, naslov, password) VALUES ('Nina', 'Peršič', 'ninapersic', 'nina.persic@gmail.com', 'Na Mlaki 1, 4240 Radovljica', 'geslo');
INSERT INTO izdelki (cena, nazivIzdelka, zalogaIzdelka) VALUES (45, 'Likalnik', 5);
INSERT INTO izdelki (cena, nazivIzdelka, zalogaIzdelka) VALUES (3, 'Sladoled', 50);
INSERT INTO izdelki (cena, nazivIzdelka, zalogaIzdelka) VALUES (2, 'Špageti', 150);
INSERT INTO izdelki (cena, nazivIzdelka, zalogaIzdelka) VALUES (170, 'Fotoaparat', 6);
INSERT INTO izdelki (cena, nazivIzdelka, zalogaIzdelka) VALUES (6, 'Beli medvedek', 12);
INSERT INTO izdelki (cena, nazivIzdelka, zalogaIzdelka) VALUES (18, 'Set avtomobilov', 5);
INSERT INTO izdelki (cena, nazivIzdelka, zalogaIzdelka) VALUES (35, 'Sence MAC', 9);
INSERT INTO izdelki (cena, nazivIzdelka, zalogaIzdelka) VALUES (5, 'Barva za lase', 15);
INSERT INTO izdelki (cena, nazivIzdelka, zalogaIzdelka) VALUES (8, 'Ženske kopalke', 25);
INSERT INTO izdelki (cena, nazivIzdelka, zalogaIzdelka) VALUES (5, 'Moške kopalke', 20);
INSERT INTO kategorije (nazivKategorije) VALUES ('Tehnika');
INSERT INTO kategorije (nazivKategorije) VALUES ('Prehrana');
INSERT INTO kategorije (nazivKategorije) VALUES ('Igrače');
INSERT INTO kategorije (nazivKategorije) VALUES ('Kozmetika');
INSERT INTO kategorije (nazivKategorije) VALUES ('Plavalna oprema');
