kumuluzee:
  name: nakupovalniSeznami
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc-seznami
      connection-url: jdbc:postgresql://192.168.99.100:5432/nakupovalniseznami
      username: postgres
      password: postgres
      max-pool-size: 20
  security:
    keycloak:
      json: '{
               "realm": "nakupovalni-seznami",
               "bearer-only": true,
               "auth-server-url": "http://192.168.99.100:9080/auth",
               "ssl-required": "external",
               "resource": "nakupovalni-seznami-api"
             }'