kumuluzee:
  name: nakupovalniSeznami
  version: 1.0.0
  env:
    name: nakupovalni_seznami
  datasources:
    - jndi-name: jdbc-seznami
      connection-url: jdbc:postgresql://localhost:5432/nakupovalniseznami
      username: postgres
      password: postgres
      max-pool-size: 20
